"""add price_on_call

Revision ID: 8f6a1461a1df
Revises: c14ef157ee99
Create Date: 2026-05-21 09:54:44.958056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6a1461a1df'
down_revision: Union[str, None] = 'c14ef157ee99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_financing_requests_created_at'), 'financing_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_appointments_created_at'), 'service_appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_ins_created_at'), 'trade_ins', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.add_column(
    'vehicles',
        sa.Column(
            'price_on_call',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    # remove the default after existing rows are populated
    op.alter_column(
        'vehicles',
        'price_on_call',
        server_default=None
    )
    op.create_index(op.f('ix_vehicles_created_at'), 'vehicles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicles_featured'), 'vehicles', ['featured'], unique=False)
    op.create_index(op.f('ix_vehicles_price'), 'vehicles', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_price'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_featured'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_at'), table_name='vehicles')
    op.drop_column('vehicles', 'price_on_call')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_trade_ins_created_at'), table_name='trade_ins')
    op.drop_index(op.f('ix_service_appointments_created_at'), table_name='service_appointments')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_financing_requests_created_at'), table_name='financing_requests')
    # ### end Alembic commands ###
