"""marketplace initial

Revision ID: 9785d782099a
Revises: 
Create Date: 2026-05-20 16:05:26.837863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9785d782099a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
    'users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(255)),
    sa.Column('email', sa.String(255)),
    sa.PrimaryKeyConstraint('id')
)
    op.execute("DROP TYPE IF EXISTS vehiclecondition CASCADE")
    op.execute("DROP TYPE IF EXISTS tradeinstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS transmissiontype CASCADE")
    op.execute("DROP TYPE IF EXISTS fueltype CASCADE")
    op.execute("DROP TYPE IF EXISTS vehiclestatus CASCADE")
    op.execute("DROP TYPE IF EXISTS employmentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS creditscorerange CASCADE")
    op.execute("DROP TYPE IF EXISTS financingstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS reviewstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS servicetype CASCADE")
    op.execute("DROP TYPE IF EXISTS appointmentstatus CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_ins',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('condition', sa.Enum('excellent', 'good', 'fair', 'poor', name='vehiclecondition', create_type=False), nullable=False),
    sa.Column('accident_history', sa.Boolean(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valuation_notes', sa.Text(), nullable=True),
    sa.Column('appraised_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'under_review', 'appraised', 'accepted', 'rejected', name='tradeinstatus', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transmission', sa.Enum('automatic', 'manual', 'cvt', 'dct', name='transmissiontype', create_type=False), nullable=False),
    sa.Column('fuel_type', sa.Enum('gasoline', 'diesel', 'electric', 'hybrid', 'plug_in_hybrid', name='fueltype', create_type=False), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('available', 'sold', 'reserved', 'pending', name='vehiclestatus', create_type=False), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_make'), 'vehicles', ['make'], unique=False)
    op.create_index(op.f('ix_vehicles_model'), 'vehicles', ['model'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_index(op.f('ix_vehicles_year'), 'vehicles', ['year'], unique=False)
    op.create_table('financing_requests',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'retired', 'unemployed', name='employmentstatus', 	create_type=False), nullable=False),
    sa.Column('employer_name', sa.String(length=120), nullable=True),
    sa.Column('years_employed', sa.Integer(), nullable=True),
     sa.Column(
    'credit_score_range',
    sa.Enum(
        'excellent',
        'good',
        'fair',
        'poor',
        'bad',
        name='creditscorerange',
        create_type=False
    ),
    nullable=False
),
    sa.Column('down_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'approved', 'rejected', 'cancelled', name='financingstatus', create_type=False), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_appointments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('service_type', sa.Enum('oil_change', 'tire_rotation', 'brake_service', 'engine_diagnostic', 'transmission_service', 'ac_service', 'general_inspection', 'test_drive', 'other', name='servicetype', create_type=False), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointmentstatus', create_type=False), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    ) 